# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Rishika Gopinath's Portfolio"
subtitle: "A chapter from my life"
author:  "Rishika Gopinath"
header:
 title: "Portfolio"
 subtitle: "by Rishika Gopinath"
footer:
 name: "Hey there, I'm Rishika "
 bio: "a content writer and editor at"
social_urls:
  twitter: "#"
  instagram: "https://www.instagram.com/rishky.business/"
  linkedin: "#"
  github: "#"
